<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="Lusamine.DamageCalc"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ElsaMina.Core\ElsaMina.Core.csproj"/>
        <ProjectReference Include="..\ElsaMina.DataAccess\ElsaMina.DataAccess.csproj"/>
        <ProjectReference Include="..\ElsaMina.LanguageModel\ElsaMina.LanguageModel.csproj"/>
        <ProjectReference Include="..\ElsaMina.Logging\ElsaMina.Logging.csproj"/>
        <ProjectReference Include="..\ElsaMina.Showdown\ElsaMina.Showdown.csproj"/>
    </ItemGroup>

</Project>
