<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="Autofac.Extensions.DependencyInjection" />
        <PackageReference Include="Lusamine.ImageIdentifier" />
        <PackageReference Include="Lusamine.WebSocketClient"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
        <PackageReference Include="NCalcSync"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ElsaMina.Logging\ElsaMina.Logging.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ElsaMina.UnitTests"/>
    </ItemGroup>

</Project>
